name: zakazky_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.3.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  timezone: ^0.10.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  mailer: ^6.0.0
  share_plus: ^11.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
